#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill --randomize $HOME/Downloads/images/* &
pulseaudio --kill
systemctl --user disable pulseaudio
systemctl --user enable pulseaudio
pulseaudio --start
$HOME/.config/polybar/scripts/polybarstart.sh &

#### MONITORS ####

bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d I II III IV V

#### CONFIG ####

bspc config border_width         1
bspc config window_gap          10
bspc config split_ratio          0.5
bspc config top_padding		10
bspc config normal_border_color	"#2e3440"
bspc config focused_border_color "#f7768e"
bspc config border_radius 	10
